options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: sh
    args:
      - -c
      - |
        gsutil -m cp -r gs://bighack-berlin-build-cache/node_modules . || true

  - name: node:22-alpine
    entrypoint: sh
    args:
      - -c
      - npm ci --quiet

  - name: node:22-alpine
    entrypoint: sh
    args:
      - -c
      - npm run build

  - name: gcr.io/cloud-builders/gsutil
    entrypoint: sh
    args:
      - -c
      - |
        gsutil -m cp -r ./node_modules gs://bighack-berlin-build-cache/node_modules || true

  - name: gcr.io/cloud-builders/gsutil
    args:
      - -m
      - rsync
      - -r
      - -d
      - ./out
      - gs://trackwinner-lol
